In [2]:
import numpy as np
print(np.version)
print(np.show_config())

<module 'numpy.version' from 'C:\\Users\\ravali\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ravali/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ravali/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ravali/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include'

In [3]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [2]:
import numpy as np
x=np.array([1,2,3,4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x=np.array([0,1,2,3])
print("original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))


Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [3]:
import numpy as np
x=np.array([1,0,0,0])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is non zero:")
print(np.any(x))
x=np.array([0,0,0,0])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is  non zero:")
print(np.any(x))


Original array:
[1 0 0 0]
Test if none of the elementsof the said array is non zero:
True
Original array:
[0 0 0 0]
Test if none of the elementsof the said array is  non zero:
False


In [4]:
import numpy as np
a=np.array([1,0,np.nan,np.inf])
print("Original array:")
print(a)
print("Test a given array element-wise for finiteness:")
print(np.isfinite(a))


Original array:
[ 1.  0. nan inf]
Test a given array element-wise for finiteness:
[ True  True False False]


In [5]:
import numpy as np
a=np.array([1,0,np.nan,np.inf])
print("Original array:")
print(a)
print("test element -wise for positive or negative infinity:")
print(np.isinf(a))

Original array:
[ 1.  0. nan inf]
test element -wise for positive or negative infinity:
[False False False  True]


In [6]:
import numpy as np
a=np.array([1,0,np.nan,np.inf])
print("Original array")
print(a)
print("test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
test element-wise for NaN:
[False False  True False]


In [9]:
import numpy as np
a=np.array([1+1j,1+0j,4.5,3,2,2j])
print("Original array")
print(a)
print("checking for complex number:")
print(np.iscomplex(a))
print("checking for real number:")
print(np.isreal(a))
print("checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))


Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
checking for complex number:
[ True False False False False  True]
checking for real number:
[False  True  True  True  True False]
checking for scalar type:
True
False


In [16]:
import numpy as np
print("Test if two arrays are element wise equal within a tolerance:")
print(np.allclose([1e10,1e-7],[1.0000e10,1e-8]))
print(np.allclose([1e10,1e-8],[1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8],[1.0001e10,1e-9]))
print(np.allclose([1.0,np.nan],[1.0,np.nan]))
print(np.allclose([1.0,np.nan],[1.0,np.nan], equal_nan=True))


Test if two arrays are element wise equal within a tolerance:
False
True
False
False
True


In [21]:
import numpy as np
x=np.array([3,5])
y=np.array([2,5])
print("Original numbers:")
print(x)
print(y)
print("comparison-greater")
print(np.greater(x,y))
print("comparison-greater_equal")
print(np.greater_equal(x,y))
print("comparision -less")
print(np.less(x,y))
print("comparison-less_equal")
print(np.less_equal(x,y))

Original numbers:
[3 5]
[2 5]
comparison-greater
[ True False]
comparison-greater_equal
[ True  True]
comparision -less
[False False]
comparison-less_equal
[False  True]


In [23]:
import numpy as np
x=np.array([72,79,85,90,150,-135,120,-10,60,100])
y=np.array([72,79,85,90,150,-135,120,-10,60,100.000001])
print("Original numbers")
print(x)
print(y)
print("comparison-equal:")
print(np.equal(x,y))
print("comparison -equal within a tolerance:")
print(np.allclose(x,y))

Original numbers
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
comparison-equal:
[ True  True  True  True  True  True  True  True  True False]
comparison -equal within a tolerance:
True


In [26]:
import numpy as np
x=np.array([1,7,13,105])
print("Original array:")
print(x)
print("size of the memory occupied by the said array:")
print("%d bytes" %(x.size* x.itemsize))

Original array:
[  1   7  13 105]
size of the memory occupied by the said array:
16 bytes


In [28]:
import numpy as np
array=np.zeros(10)
print("an array of 10 zeros:")
print(array)
array=np.ones(10)
print("an array of 10 ones:")
print(array)
array=np.ones(10)*5
print("an array of 10 fives:")
print(array)

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
an array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
an array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [30]:
import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to 71")
print(array)

Array of the integers from 30 to 71
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [34]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the integers from 30 to 71")
print(array)

Array of all the integers from 30 to 71
[30 35 40 45 50 55 60 65 70]


In [37]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
import numpy as np
rand_num=np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[0.29206374 0.86014718]


In [41]:
import numpy as np
rand_num=np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[-0.21250612 -0.46331885  0.15030655  0.34699856 -0.03844374 -1.46681019
  0.12864367  0.02778419  0.81693234 -0.62420275 -0.23192445  1.41622631
 -1.4874332  -0.57460176 -0.78581987]


In [42]:
import numpy as np
v=np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [50]:
import numpy as np
a=np.arange(10,22).reshape((3,4))
print("original array:")
print(a)
print("Each element of the array is:")
print(x)

original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
[  1   7  13 105]


In [51]:
import numpy as np
v=np.linspace(10,49,5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


In [52]:
import numpy as np
x=np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15")
x[(x>=9)&(x<=15)] *=-1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [53]:
import numpy as np
x=np.random.randint(0,11,5)
print("vector of length 5 filled with arbitrary from 0 to 10:")
print(x)

vector of length 5 filled with arbitrary from 0 to 10:
[ 6  6 10  5  4]


In [54]:
import numpy as np
x=np.array([1,8,3,5])
print("vector-1")
print(x)
y=np.random .randint(0,11,4)
print("vector -2")
print(y)
result=x*y
print("Multiply the values of two said vectors:")
print(result)

vector-1
[1 8 3 5]
vector -2
[10  2  6  7]
Multiply the values of two said vectors:
[10 16 18 35]


In [57]:
import numpy as np
m=np.arange(10,22).reshape((3,4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [61]:
import numpy as np
m=np.arange(10,22).reshape((3,4))
print("Original matrix:")
print(m)
print("Number of rows and coloumns of the said matrix:")
print(m.shape)

Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and coloumns of the said matrix:
(3, 4)


In [66]:
import numpy as np
m=np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [71]:
import numpy as np
x=np.ones((10,10))
x[1:-1, 1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [74]:
import numpy as np
m=np.diag([1,2,3,4,5])
print(m)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [75]:
import numpy as np
x=np.zeros((4,4))
x[::2, 1::2] =1
x[1::2, ::2]=1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [76]:
import numpy as np
x=np.random.random((3,3,3))
print(x)

[[[0.45591769 0.75756569 0.64264567]
  [0.62564459 0.12751569 0.32705946]
  [0.73247479 0.83440017 0.71052022]]

 [[0.6623026  0.34947447 0.11607571]
  [0.04630767 0.60581039 0.84090553]
  [0.44893617 0.08309316 0.63931006]]

 [[0.35606393 0.28965614 0.50821738]
  [0.09422617 0.65932587 0.09972013]
  [0.41092852 0.21497575 0.7093786 ]]]


In [2]:
import numpy as np
x=np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x,axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [3]:
import numpy as np
x=np.array([4,5])
y=np.array([7,10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x,y))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [19]:
import numpy as np
m=np.array([1,2,3],[4,5,6],[7,8,9],[10,11,12])
v=np.array([1,1,0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result=np.empty_like(m)
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

ValueError: only 2 non-keyword arguments accepted

In [16]:
import numpy as np
import os
a=np.arange(20)
np.save('temp_array.npy',a)
print("check if'temp_array.npy'exists or not?")
if os.path.exists('temp_array.npy'):
   x2=np.load('temp_array.npy')
   print(np.array_equal(a,x2))
    

check if'temp_array.npy'exists or not?
True


In [15]:
import numpy as np
import os
x=np.arange(10)
y=np.arange(11,20)
print("Original arrays:")
print(x)
print(y)
np.savez('temp_arra.npz',x=x,y=y)
print("Load arrays from the'temp_arra.npz' file:")
with np.load('temp_arra.npz')as data:
      x2= data['x']
      y2= data['y']
      print(x2)
      print(y2)

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [20]:
import numpy as np
import os
x=np.arange(12).reshape(4,3)
print("Original array:")
print(x)
header='col1 col2 col3'
np.savetxt('temp.txt',x,fmt="%d",header=header)
print("After loading, content of the text file:")
result=np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [21]:
import numpy as np
import os
a=np.array([1,2,3,4,5,6])
print("Original array:")
print(a)
a_bytes=a.tobytes()
a2=np.frombuffer(a_bytes,dtype=a.dtype)
print("After loading, content of the text file:")
print(a2)
print(np.array_equal(a,a2))



Original array:
[1 2 3 4 5 6]
After loading, content of the text file:
[1 2 3 4 5 6]
True


In [22]:
import numpy as np
a=[[1,2],[3,4]]
x=np.array(a)
a2=x.tolist()
print(a==a2)

True


In [23]:
import numpy as np
import matplotlib.pyplot as plt
#compute the X and Y coordiates for points on a sine curve
x=np.arange(0,3*np.pi,0.2)
y=np.sin(x)
print("Plot the points using matplotlib:")
plt.plot(x,y)
plt.show()

Plot the points using matplotlib:


<Figure size 640x480 with 1 Axes>

In [24]:
import numpy as np
print("numpy.float32 to python float")
x=np.float32(0)
print(type(x))
pyval=x.item()
print(type(pyval))


numpy.float32 to python float
<class 'numpy.float32'>
<class 'float'>


In [54]:
import numpy as np
def sum_matrix_Elements(m):
    arra = np.array(m)
    element_sum= 0
    for p in range(len(arra)):
        for q in range(len(arra[p])):
             if arra[p] [q]==0 and p<len(arra)-1:
                  arra[p+1][q] = 0
              element_sum += arra[p][q]
       return element_sum
 m =  [[1, 1, 0, 2], 
           [0, 3, 0, 3],
           [1, 0, 4, 4]]
    print("Original matrix:")
    print(m)
    print("sum:")
    print(sum_matrix_Elements(m))
          

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [57]:
import numpy as np
nums=np.array([[3, 2, np.nan, 1],
              [10, 12, 10, 9],
              [5, np.nan, 1, np.nan]])
print("Original array:")
print(nums)
print("/nFind the missing data of the said array:")
print(np.isnan(nums))

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
/nFind the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [58]:
import numpy as np
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2))

Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

Test said two arrays are equal (element wise) or not:?
[False False  True]


In [59]:
import numpy as np
nums=np.arange(1,21)
print("One-dimensional array of single digit numbers:")
print(nums)
nums = np.arange(10, 21)
print("\nOne-dimensional array of two digit numbers:")
print(nums)
nums=np.arange(100,201)
print("\nOne=dimensional array of three digit numbers:")
print(nums)



One-dimensional array of single digit numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

One-dimensional array of two digit numbers:
[10 11 12 13 14 15 16 17 18 19 20]

One=dimensional array of three digit numbers:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


In [60]:
import numpy as np
print("create an array of shape (15,10):")
print("command-1")
print(np.arange(1, 151).reshape(15,10))
print("\nCommand-2")
print(np.arange(1, 151).reshape(-1, 10))
print("/nCommand-3")
print(np.arange(1,151).reshape(15, -1))


create an array of shape (15,10):
command-1
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]

Command-2
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70

In [61]:
import numpy as np
np.random.seed(10)
print(np.random.rand(40))

[0.771320643266746 0.020751949359402 0.633648234926275 0.748803882538612
 0.49850701230259  0.224796645530848 0.198062864759624 0.760530712198959
 0.169110836562535 0.08833981417401  0.685359818367797 0.953393346194937
 0.003948266327914 0.512192263385777 0.812620961652114 0.612526066829388
 0.7217553174318   0.291876068170633 0.917774122512943 0.714575783397691
 0.542544368011261 0.142170047601527 0.373340760051469 0.674133615066345
 0.441833174422996 0.434013993333294 0.617766978469317 0.513138242554391
 0.650397181931467 0.601038953404544 0.805223196832746 0.521647152393634
 0.908648880808668 0.319236088988545 0.090459349270907 0.300700056636203
 0.11398436186355  0.828681326307677 0.04689631938925  0.626287148311393]


In [62]:
import numpy as np
np.random .seed(20)
cbrt=np.cbrt(7)
nd1 = 200
print(cbrt *np.random.randn(10,4) + nd1)

[[201.69082669736346 200.3746763082702  200.68394275021677
  195.51750123129818]
 [197.92478991563303 201.07066048488275 201.79714021459858
  198.12823310277952]
 [200.96238963339914 200.77744291067876 200.61875865227867
  199.05613893807728]
 [198.48492638364303 198.38860811141893 197.55239946005003
  200.47003620983824]
 [199.9154583876559  202.99877319355295 202.01069856971475
  200.77735483308504]
 [199.67739161408255 193.89831807071494 202.14273592752286
  202.54951299405823]
 [199.53450968631876 199.75126019761723 199.791457270905
  202.97687756587686]
 [200.24634412660365 196.0460693352411  198.3061125324022
  197.88701546225133]
 [201.7845091237894  203.94032834458278 198.21152802602944
  196.9144607143198 ]
 [201.0082480992413  197.03285103581035 200.6305276348363
  197.82590294139914]]


In [63]:
import numpy as np 
print("Generate a uniform random sample with replacement:") 
print(np.random.choice(7, 5))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False))
print("\nGenerate a non-uniform random sample with replacement:") 
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))  

Generate a uniform random sample with replacement:
[2 2 1 5 2]

Generate a uniform random sample without replacement:
[6 3 5 4 2]

Generate a non-uniform random sample with replacement:
[6 1 6 0 1]

Generate a uniform random sample without replacement:
[1 6 4 3 0]


In [64]:
import numpy as np
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
nums[[0,-1],:]=nums[[-1,0],:]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
